name: Push a new tag to datahub repo
on:
  workflow_dispatch:

jobs:
  push-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Set up git
        run: |
          echo https://x-access-token:${GITHUB_TOKEN}@github.com > ~/.git-credentials

      - name: Clone the datahub repo
        run: git clone https://github.com/berkeley-dsep-infra/datahub.git

      - name: Push tag to datahub repo
        run: |
            tag=$(date '+%Y%m%d-%H%M%S')
            cd datahub/

            git config credential.helper store
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git tag ${tag}
            git push origin ${tag}
