name: Push a new tag to datahub repo
on:
  workflow_dispatch:

jobs:
  push-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Set up git
        run: |
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"

      - name: Clone the datahub repo
        run: git clone https://github.com/berkeley-dsep-infra/datahub.git

      - name: Push tag to datahub repo
        run: |
            tag=$(date '+%Y%m%d-%H%M%S')
            cd datahub/
            git tag ${tag}
            git push https://x-access-token:${{ secrets.PUSH_TAG_TOKEN }}@github.com/berkeley-dsep-infra/datahub.git ${tag}
