name: Push a new tag to datahub repo
on:
  workflow_dispatch:

jobs:
  push-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Set up git
        run: git config --global url."https://x-access-token:${{ secrets.PUSH_TAG_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Clone the datahub repo
        run: |
          git clone --branch staging https://github.com/berkeley-dsep-infra/datahub.git datahub

      - name: Push tag to datahub repo
        run: |
            tag=$(date '+%Y%m%d-%H%M%S')
            cd datahub/

            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git tag ${tag}
            git push origin ${tag}
